create database Test;
use test;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT * FROM mytable LIMIT 20;
select Gender, sum(purchase_amount) as revenue
from mytable
group by Gender;

-- Q2. which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM mytable
WHERE discount_applied = "Yes" 
AND purchase_amount >= (SELECT AVG(purchase_amount) From mytable);


-- Q3. which are the top 5 products with the highest average review rating?

SELECT item_purchased, AVG(review_rating) AS "Average Product Rating"
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5; 

-- Q4. compare the average purchase amounts between standard and Express shipping.
SELECT shipping_type,
AVG(purchase_amount)
FROM mytable
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. do subscribed customers spend more? compare average spend and total revenue  between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. which 5 products have the highest percentage of purchase with discount applied?
SELECT item_purchased,
100* SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END)/COUNT(*) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. segment customers into new, returning, and loyal based on their total number of previous purchase, and show the cunt of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM mytable)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. what are the top 3 most purchsed product within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. what is the revenue contribution of ech age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;

